"""empty message

Revision ID: 1a125f84a3a7
Revises: 866692f43995
Create Date: 2022-08-07 10:36:11.136742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a125f84a3a7'
down_revision = '866692f43995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'user_movie_genres', 'users_films', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'user_movie_genres', 'movies_database', ['movie_id'], ['id'])
    # ### end Alembic commands ###
