"""empty message

Revision ID: 295990814279
Revises: 5816e3e5e3de
Create Date: 2022-08-06 22:45:38.856724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295990814279'
down_revision = '5816e3e5e3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_suggestion', sa.Column('img_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_suggestion', 'img_url')
    # ### end Alembic commands ###
