"""inital migration

Revision ID: 3d44b5213f94
Revises: 
Create Date: 2022-07-14 00:25:39.713310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d44b5213f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('ranking', sa.String(length=500), nullable=True))
    op.add_column('users_films', sa.Column('user_rating', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_films', 'user_rating')
    op.drop_column('users_films', 'ranking')
    # ### end Alembic commands ###
