"""empty message

Revision ID: 4433d528e0b7
Revises: af0218eff663
Create Date: 2022-07-25 10:48:59.178248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433d528e0b7'
down_revision = 'af0218eff663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users_films', 'movies_database', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_films', type_='foreignkey')
    # ### end Alembic commands ###
