"""empty message

Revision ID: 5d128ea0a9cb
Revises: af68f6d363bf
Create Date: 2022-07-28 19:25:30.409860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d128ea0a9cb'
down_revision = 'af68f6d363bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users_films', 'movies_database', ['movie_id'], ['id'])
    op.drop_column('users_films', 'ranking')
    op.drop_column('users_films', 'user_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('user_rating', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('ranking', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'users_films', type_='foreignkey')
    # ### end Alembic commands ###
