"""empty message

Revision ID: 5f9c18abbabb
Revises: 7ce6bf1ff003
Create Date: 2022-08-06 21:36:37.798004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9c18abbabb'
down_revision = '7ce6bf1ff003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_actors', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('movie_actors', sa.Column('main_cast', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'movie_actors', type_='foreignkey')
    op.drop_constraint(None, 'movie_actors', type_='foreignkey')
    op.drop_column('movie_actors', 'movie_id')
    op.drop_column('movie_actors', 'actor_id')
    op.add_column('user_movie_actors', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_movie_actors', sa.Column('main_cast', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'user_movie_actors', type_='foreignkey')
    op.drop_constraint(None, 'user_movie_actors', type_='foreignkey')
    op.drop_column('user_movie_actors', 'actor_id')
    op.drop_column('user_movie_actors', 'user_movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movie_actors', sa.Column('user_movie_id', sa.INTEGER(), nullable=True))
    op.add_column('user_movie_actors', sa.Column('actor_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user_movie_actors', 'users_films', ['user_movie_id'], ['id'])
    op.create_foreign_key(None, 'user_movie_actors', 'actors', ['actor_id'], ['id'])
    op.drop_column('user_movie_actors', 'main_cast')
    op.drop_column('user_movie_actors', 'id')
    op.add_column('movie_actors', sa.Column('actor_id', sa.INTEGER(), nullable=True))
    op.add_column('movie_actors', sa.Column('movie_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'movie_actors', 'movies_database', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_actors', 'actors', ['actor_id'], ['id'])
    op.drop_column('movie_actors', 'main_cast')
    op.drop_column('movie_actors', 'id')
    # ### end Alembic commands ###
