"""empty message

Revision ID: 6e70eb9463d7
Revises: ebb4efbd2a5f
Create Date: 2022-08-05 12:31:45.627038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e70eb9463d7'
down_revision = 'ebb4efbd2a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_actors', 'user_movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_actors', sa.Column('user_movie_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
