"""empty message

Revision ID: 7ce6bf1ff003
Revises: 6e70eb9463d7
Create Date: 2022-08-05 12:47:42.602849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce6bf1ff003'
down_revision = '6e70eb9463d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_actors', type_='foreignkey')
    op.drop_column('user_movie_actors', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movie_actors', sa.Column('movie_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user_movie_actors', 'movies_database', ['movie_id'], ['id'])
    # ### end Alembic commands ###
