"""empty message

Revision ID: 866692f43995
Revises: 295990814279
Create Date: 2022-08-07 10:34:13.481682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866692f43995'
down_revision = '295990814279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'user_movie_genres', 'users_films', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'user_movie_genres', 'movies_database', ['movie_id'], ['id'])
    # ### end Alembic commands ###
