"""empty message

Revision ID: af0218eff663
Revises: b8b68ecf6d27
Create Date: 2022-07-24 02:27:01.135428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0218eff663'
down_revision = 'b8b68ecf6d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users_films', 'movies_database', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_films', type_='foreignkey')
    op.drop_column('users_films', 'movie_id')
    # ### end Alembic commands ###
