"""empty message

Revision ID: af68f6d363bf
Revises: 4433d528e0b7
Create Date: 2022-07-28 19:17:56.778660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af68f6d363bf'
down_revision = '4433d528e0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_cast', 'role')
    op.create_foreign_key(None, 'users_films', 'movies_database', ['movie_id'], ['id'])
    op.drop_column('users_films', 'user_rating')
    op.drop_column('users_films', 'ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('ranking', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('user_rating', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'users_films', type_='foreignkey')
    op.add_column('movie_cast', sa.Column('role', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
