"""empty message

Revision ID: b12a51cbcb6e
Revises: 2c08257d1b69
Create Date: 2022-07-28 19:30:58.227050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12a51cbcb6e'
down_revision = '2c08257d1b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users_films', 'movies_database', ['movie_id'], ['id'])
    op.drop_column('users_films', 'user_rating')
    op.drop_column('users_films', 'ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('ranking', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('user_rating', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'users_films', type_='foreignkey')
    # ### end Alembic commands ###
