"""empty message

Revision ID: b8b68ecf6d27
Revises: 3886b7b3af47
Create Date: 2022-07-24 02:22:37.215723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b68ecf6d27'
down_revision = '3886b7b3af47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_films', 'writer')
    op.drop_column('users_films', 'producer')
    op.drop_column('users_films', 'boxoffice')
    op.drop_column('users_films', 'studio')
    op.drop_column('users_films', 'runtine')
    op.drop_column('users_films', 'user_score')
    op.drop_column('users_films', 'description')
    op.drop_column('users_films', 'director')
    op.drop_column('users_films', 'PG')
    op.drop_column('users_films', 'computed_audience_score')
    op.drop_column('users_films', 'collection')
    op.drop_column('users_films', 'user_reviews_no')
    op.drop_column('users_films', 'critic_reviews_no')
    op.drop_column('users_films', 'genre')
    op.drop_column('users_films', 'cast')
    op.drop_column('users_films', 'PG_text')
    op.drop_column('users_films', 'certified')
    op.drop_column('users_films', 'release_date')
    op.drop_column('users_films', 'rotten_url')
    op.drop_column('users_films', 'computed_critic_score')
    op.drop_column('users_films', 'img_url')
    op.drop_column('users_films', 'tomatometer')
    op.drop_column('users_films', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_films', sa.Column('title', sa.VARCHAR(length=300), nullable=True))
    op.add_column('users_films', sa.Column('tomatometer', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('img_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('computed_critic_score', sa.INTEGER(), nullable=True))
    op.add_column('users_films', sa.Column('rotten_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('release_date', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users_films', sa.Column('certified', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('PG_text', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('users_films', sa.Column('cast', sa.VARCHAR(length=3000), nullable=True))
    op.add_column('users_films', sa.Column('genre', sa.VARCHAR(length=3000), nullable=True))
    op.add_column('users_films', sa.Column('critic_reviews_no', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('user_reviews_no', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('collection', sa.VARCHAR(length=300), nullable=True))
    op.add_column('users_films', sa.Column('computed_audience_score', sa.INTEGER(), nullable=True))
    op.add_column('users_films', sa.Column('PG', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('director', sa.VARCHAR(length=3000), nullable=True))
    op.add_column('users_films', sa.Column('description', sa.VARCHAR(length=5000), nullable=True))
    op.add_column('users_films', sa.Column('user_score', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('runtine', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('studio', sa.VARCHAR(length=3000), nullable=True))
    op.add_column('users_films', sa.Column('boxoffice', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users_films', sa.Column('producer', sa.VARCHAR(length=3000), nullable=True))
    op.add_column('users_films', sa.Column('writer', sa.VARCHAR(length=3000), nullable=True))
    # ### end Alembic commands ###
