"""empty message

Revision ID: c178ddb9dd9a
Revises: 4fe352f591fe
Create Date: 2022-08-06 21:54:29.868082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c178ddb9dd9a'
down_revision = '4fe352f591fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_actors', 'id')
    op.drop_column('movie_actors', 'main_cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_actors', sa.Column('main_cast', sa.BOOLEAN(), nullable=True))
    op.add_column('movie_actors', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
