"""empty message

Revision ID: e01f51db1a4e
Revises: 48df49572762
Create Date: 2022-08-05 00:17:57.462701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01f51db1a4e'
down_revision = '48df49572762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_suggestion', sa.Column('img_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_suggestion', 'img_url')
    # ### end Alembic commands ###
