"""str to int

Revision ID: e59ef0b54fa3
Revises: 0b951a992f6e
Create Date: 2022-07-22 03:01:20.447971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59ef0b54fa3'
down_revision = '0b951a992f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_suggestions', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_suggestions', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_suggestions', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_suggestions', 'id')
    # ### end Alembic commands ###
